
server:
  port: 8082


spring:
  data:
    maria:
      jdbc-url: jdbc:mariadb://rds-mariadb.cqhcxporxber.ap-northeast-2.rds.amazonaws.com:3306/admin?useUnicode=yes&characterEncoding=UTF-8
      driver-class-name: org.mariadb.jdbc.Driver
      username: admin
      password: ke807843
  jpa:
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    generate-ddl: true